# Generated by Django 4.1.1 on 2024-02-23 11:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('shortcut', models.CharField(max_length=5, unique=True)),
                ('currency', models.CharField(default='Afg', max_length=5)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20, unique=True)),
                ('city', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.country')),
            ],
            options={
                'unique_together': {('country', 'state', 'city')},
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('organization_type', models.CharField(max_length=25)),
                ('created_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('img', models.FileField(blank=True, null=True, upload_to='Organization', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])])),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.location', to_field='city')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.organization', to_field='name')),
            ],
            options={
                'unique_together': {('name', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('order', models.IntegerField()),
                ('created_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.organization', to_field='name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.role')),
            ],
            options={
                'unique_together': {('name', 'parent', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='Language_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_field', models.CharField(blank=True, max_length=40, null=True)),
                ('src', models.CharField(max_length=15, null=True)),
                ('text', models.TextField(default=None)),
                ('value', models.TextField(null=True)),
                ('dest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='configuration.languages')),
            ],
            options={
                'verbose_name_plural': 'Language Detail',
                'unique_together': {('id_field', 'src', 'dest', 'value')},
            },
        ),
    ]
