# Generated by Django 4.1.1 on 2022-10-18 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language_detail',
            old_name='language',
            new_name='languages',
        ),
        migrations.AlterUniqueTogether(
            name='language_detail',
            unique_together={('languages', 'key')},
        ),
    ]
