# Generated by Django 4.2 on 2025-07-25 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together=set(),
        ),
    ]
