# Generated by Django 4.2 on 2025-11-08 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_alter_organization_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='parent',
        ),
    ]
