# Generated by Django 4.1.1 on 2022-10-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_rename_language_language_detail_languages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language_detail',
            name='value',
            field=models.TextField(null=True),
        ),
    ]
