# Generated by Django 4.2 on 2025-03-08 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_customuser_customuser_valid_user_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language_Detail',
        ),
    ]
