# Generated by Django 4.2 on 2025-05-02 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_organization_location_new_organization_parent_new_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='location',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='parent',
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('name', 'parent')},
        ),
        migrations.DeleteModel(
            name='Language_Detail',
        ),
        migrations.DeleteModel(
            name='Languages',
        ),
        migrations.RemoveField(
            model_name='role',
            name='organization',
        ),
    ]
