# Generated by Django 4.2 on 2025-05-02 05:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_remove_organization_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='location_new',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='parent_new',
            new_name='parent',
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='role',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.organization'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('name', 'parent', 'organization')},
        ),
    ]
