# Generated by Django 4.1.1 on 2022-10-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_alter_language_detail_key'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='language_detail',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='language_detail',
            name='id_field',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='language_detail',
            name='src',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='language_detail',
            name='text',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='language_detail',
            unique_together={('text', 'id_field')},
        ),
        migrations.RemoveField(
            model_name='language_detail',
            name='key',
        ),
        migrations.RemoveField(
            model_name='language_detail',
            name='page',
        ),
    ]
