# Generated by Django 6.0 on 2025-12-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_type',
            field=models.CharField(blank=True, default='main', max_length=20, null=True),
        ),
    ]
