# Generated by Django 4.1.1 on 2022-10-21 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_alter_language_detail_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language_detail',
            old_name='languages',
            new_name='dest',
        ),
    ]
