# Generated by Django 4.2 on 2025-05-02 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_rename_location_new_organization_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.location'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.organization'),
        ),
    ]
