# Generated by Django 4.1.1 on 2022-10-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0006_rename_languages_language_detail_dest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='language_detail',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='language_detail',
            name='src',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='language_detail',
            unique_together={('text', 'id_field', 'src')},
        ),
    ]
