# Generated by Django 4.2 on 2025-03-08 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0008_organization_location_organization_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='is_active',
            new_name='is_service',
        ),
    ]
