# Generated by Django 4.1.1 on 2022-10-22 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0009_alter_language_detail_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='language_detail',
            unique_together={('id_field', 'dest', 'text', 'value')},
        ),
    ]
