# Generated by Django 4.1.1 on 2022-10-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0010_alter_language_detail_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='language_detail',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='language_detail',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='language_detail',
            unique_together={('dest', 'text', 'value')},
        ),
    ]
