# Generated by Django 4.1.1 on 2022-10-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0011_alter_language_detail_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language_detail',
            name='text',
            field=models.TextField(default=None),
        ),
    ]
