# Generated by Django 4.1.1 on 2022-10-26 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0012_alter_language_detail_text'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='language_detail',
            unique_together={('src', 'dest', 'text', 'value')},
        ),
    ]
