# Generated by Django 4.1.1 on 2022-12-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0013_alter_language_detail_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='language_detail',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='language_detail',
            name='id_field',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='language_detail',
            unique_together={('src', 'dest', 'id_field', 'value')},
        ),
    ]
