# Generated by Django 4.2 on 2025-06-17 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_stock_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_detail',
            name='unit',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.unit'),
        ),
    ]
