# Generated by Django 4.2 on 2025-06-27 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
        ('product', '0003_product_detail_unit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('organization', 'product')},
        ),
        migrations.RemoveField(
            model_name='stock',
            name='store',
        ),
    ]
