# Generated by Django 4.2 on 2025-10-07 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_stock_unique_together_remove_stock_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='loss_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=22),
        ),
    ]
