# Generated by Django 4.1.1 on 2024-03-08 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_store_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.store')),
            ],
        ),
    ]
