# Generated by Django 4.2 on 2025-12-04 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_branch'),
        ('product', '0005_stock_loss_amount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='product_detail',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch where this product is available', null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.branch'),
        ),
        migrations.AddField(
            model_name='stock',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch where this stock is held', null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.branch'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('organization', 'product', 'branch')},
        ),
    ]
