# Generated by Django 4.1.1 on 2024-03-08 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='product.store'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('store', 'product')},
        ),
    ]
