# Generated by Django 6.0 on 2026-03-04 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_branch_branch_type'),
        ('product', '0006_alter_stock_unique_together_product_detail_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch where this stock is held', null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.branch'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='organization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.organization'),
        ),
    ]
