# Generated by Django 4.2 on 2025-04-25 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_organization_location_new_organization_parent_new_and_more'),
        ('product', '0009_stock_purchasing_amount_stock_selling_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_media',
            name='service',
        ),
        migrations.RemoveField(
            model_name='service_media',
            name='uploader',
        ),
        migrations.AlterUniqueTogether(
            name='subservice',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='subservice',
            name='dest',
        ),
        migrations.RemoveField(
            model_name='subservice',
            name='service',
        ),
        migrations.RemoveField(
            model_name='subservice_media',
            name='service',
        ),
        migrations.RemoveField(
            model_name='subservice_media',
            name='uploader',
        ),
        migrations.AddField(
            model_name='product_detail',
            name='organization_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_detail_organization_set', to='configuration.organization'),
        ),
        migrations.AddField(
            model_name='row_column_address',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.store'),
        ),
        migrations.AddField(
            model_name='store',
            name='organization_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_organization_set', to='configuration.organization'),
        ),
        migrations.AddField(
            model_name='unit',
            name='organization_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_organization_set', to='configuration.organization'),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Service_Media',
        ),
        migrations.DeleteModel(
            name='SubService',
        ),
        migrations.DeleteModel(
            name='SubService_Media',
        ),
    ]
