# Generated by Django 4.2 on 2025-05-02 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_remove_organization_location_and_more'),
        ('product', '0010_remove_service_media_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_detail',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='organization',
        ),
        migrations.AlterUniqueTogether(
            name='store',
            unique_together={('name', 'organization_new')},
        ),
        migrations.RemoveField(
            model_name='store',
            name='organization',
        ),
    ]
