# Generated by Django 4.2 on 2025-03-06 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_detail_product_new_organization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_detail',
            name='organization',
        ),
    ]
