# Generated by Django 4.2 on 2025-05-02 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_rename_location_new_organization_location_and_more'),
        ('product', '0011_remove_product_detail_organization_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_detail',
            old_name='organization_new',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='organization_new',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='organization_new',
            new_name='organization',
        ),
        migrations.AlterUniqueTogether(
            name='store',
            unique_together={('organization', 'name')},
        ),
    ]
