# Generated by Django 4.2 on 2025-03-06 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_customuser_customuser_valid_user_type_and_more'),
        ('product', '0011_remove_product_detail_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_detail',
            old_name='product_new_organization',
            new_name='organization',
        ),
    ]
