# Generated by Django 4.2 on 2025-05-02 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0006_alter_organization_location_and_more'),
        ('product', '0012_rename_organization_new_product_detail_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_detail',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.organization'),
        ),
        migrations.AlterField(
            model_name='store',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.organization'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.organization'),
        ),
    ]
