"""
Django settings for shop project. 

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/  
"""

from pathlib import Path
import django_heroku
# import dj_database_url
# from decouple import config
import os
# from django.conf import settings
from django.conf.urls import static
from django.urls import path
# from django.contrib import admin
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the sfecret key used in production secret!
SECRET_KEY = 'django-insecure-$(o_^k29jw!#(g&if@=q$*zxpn(zqau986k86dq$(fi161t(*p'


MEDIA_URL='/media/'
MEDIA_ROOT=os.path.join(BASE_DIR,'media')

# print("MEDIA_ROOT ",MEDIA_ROOT)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
     "https://tejaratistan.com",
    "https://tejaratistan.herokuapp.com",
    "https://sub.example.com",
    "http://localhost:5000",
    "http://127.0.0.1:5000",
    "http://127.0.0.1:8000",
    "http://127.0.0.1:2000"
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'product',
    'expenditure',
    'user_request',
    'qrapp',
    'chat',
    'bill',
    'user',
    'configuration',
    'rest_framework',
     'corsheaders',
     'jalali_date',
    #  'asset',
]


# default settings
JALALI_DATE_DEFAULTS = {
   'Strftime': {
        'date': '%y-%m-%d',
        'datetime': '%H:%M:%S _ %y-%m-%d',
    },
    'Static': {
        'js': [
            # loading datepicker
            'admin/js/django_jalali.min.js',
            # OR
            # 'admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.core.js',
            # 'admin/jquery.ui.datepicker.jalali/scripts/calendar.js',
            # 'admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.datepicker-cc.js',
            # 'admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.datepicker-cc-fa.js',
            # 'admin/js/main.js',
        ],
        'css': {
            'all': [
                'admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css',
            ]
        }
    },
}



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'shop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,"templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'shop.wsgi.application'


# from corsheaders.defaults import default_headers

# CORS_ALLOW_HEADERS = default_headers + (
#     'Access-Control-Allow-Origin',
# )
# CORS_ALLOW_HEADERS = "*"
# CORS_ORIGIN_ALLOW_ALL = True
CORS_ORIGIN_WHITELIST = (
     "https://www.tejaratistan.com",
    "https://tejaratistan.herokuapp.com"
)
CORS_ALLOWED_ORIGINS = [
    "https://www.tejaratistan.com",
    "https://tejaratistan.herokuapp.com",
    "https://sub.example.com",
    "http://localhost:5000",
    "http://127.0.0.1:5000",
    "http://127.0.0.1:8000",
    "http://127.0.0.1:2000"
]






# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'shirkat_new.sqlite3',
#         #'NAME':'shop',
#         #'HOST':'127.0.0.1',
#         #'USER':'admin',
#         #'PASSWORD':'Allahisone',
#     }
# } 
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         # 'NAME': BASE_DIR / 'shop.sqlite3',
#         'NAME':'u456988861_bilal',
#         'HOST':'tejaratistan.com',
#         'USER':'u456988861_bilal',
#         'PASSWORD':'Allahisone1',
#     }
# } 

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        # 'NAME': BASE_DIR / 'shop.sqlite3',
        'NAME':'shirkat',
        'HOST':'localhost',
        'USER':'root',
        'PASSWORD':'',
    }
    # 'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     # 'NAME': BASE_DIR / 'shop.sqlite3',
    #     'NAME':'test',
    #     'HOST':'localhost',
    #     'USER':'root',
    #     'PASSWORD':'',
    # }
} 

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         # 'NAME': BASE_DIR / 'shop.sqlite3',
#         'NAME':'u456988861_tejaratistan',
#         'HOST':'tejaratistan.com',
#         'USER':'u456988861_root',
#         'PASSWORD':'Allahisone1',
#     }
# } 


# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_HOST_USER = 'mohammadbilalniazi2016@gmail.com'
# EMAIL_HOST_PASSWORD = 'god_is_one'
# EMAIL_USE_TLS = True
# EMAIL_PORT = 587



# EMAIL_HOST_USER = os.environ['SENDGRID_USERNAME']
EMAIL_HOST_USER ='app280201596@heroku.com'
EMAIL_HOST= 'smtp.sendgrid.net'
EMAIL_PORT = 587 
EMAIL_USE_TLS = True
EMAIL_HOST_PASSWORD ='nimhauur0474'
# EMAIL_HOST_PASSWORD = os.environ['SENDGRID_PASSWORD']

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kabul'

USE_I18N = True

USE_TZ = True
# USE_TZ = True
# TIME_ZONE = 'Europe/Paris'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/


STATIC_URL = 'static/'
STATICFILES_DIRS=(
    os.path.join(BASE_DIR, "static/"),
)

STATICFILES_STORAGE='whitenoise.storage.CompressedManifestStaticFilesStorage'
# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
django_heroku.settings(locals())
