# Generated by Django 4.2 on 2025-04-07 02:15

import bill.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.IntegerField()),
                ('bill_type', models.CharField(default='PURCHASE', max_length=11)),
                ('total', models.DecimalField(decimal_places=5, default=0.0, max_digits=20)),
                ('payment', models.DecimalField(decimal_places=5, default=0.0, max_digits=20)),
                ('year', models.SmallIntegerField(default=bill.models.get_year)),
                ('date', models.CharField(default='1404-01-18', max_length=10)),
                ('profit', models.IntegerField(default=0)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creator_set', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='configuration.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Bill_Receiver2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(blank=True, default=False, null=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('approval_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bill.bill')),
                ('bill_rcvr_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='configuration.organization')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.store')),
            ],
        ),
        migrations.CreateModel(
            name='Bill_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_amount', models.DecimalField(decimal_places=5, default=0.0, max_digits=15)),
                ('item_price', models.DecimalField(decimal_places=5, default=0.0, max_digits=15)),
                ('return_qty', models.IntegerField(blank=True, null=True)),
                ('discount', models.IntegerField(default=0)),
                ('profit', models.IntegerField(default=None, null=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.bill')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.unit')),
            ],
            options={
                'verbose_name_plural': 'Bill detail',
            },
        ),
        migrations.CreateModel(
            name='Bill_Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'CANCELLED'), (1, 'CREATED')], default=0)),
                ('currency', models.CharField(default='afg', max_length=7)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bill.bill')),
                ('shipment_location', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='configuration.location')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_store', to='product.store')),
            ],
        ),
    ]
