# Generated by Django 4.2 on 2025-06-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_alter_bill_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill_receiver2',
            name='store',
        ),
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.CharField(default='1404-04-06', max_length=10),
        ),
    ]
