# Generated by Django 4.2 on 2025-07-25 18:52

import bill.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_remove_bill_receiver2_store_alter_bill_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.CharField(default=bill.models.get_date, max_length=10),
        ),
    ]
