# Generated by Django 4.2 on 2025-09-26 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_alter_organization_unique_together'),
        ('bill', '0004_alter_bill_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='currency',
            field=models.CharField(default='afg', max_length=7),
        ),
        migrations.AddField(
            model_name='bill',
            name='shipment_location',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='configuration.location'),
        ),
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'CANCELLED'), (1, 'CREATED')], default=0),
        ),
    ]
