# Generated by Django 4.1.1 on 2024-06-15 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_currency'),
        ('bill', '0004_delete_currency'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together={('organization', 'year', 'bill_no', 'bill_type')},
        ),
    ]
