# Generated by Django 4.2 on 2025-09-26 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0005_bill_currency_bill_shipment_location_bill_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bill_Description',
        ),
    ]
