# Generated by Django 4.2 on 2025-10-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0006_delete_bill_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(choices=[('PURCHASE', 'PURCHASE'), ('SELLING', 'SELLING'), ('PAYMENT', 'PAYMENT'), ('RECEIVEMENT', 'RECEIVEMENT'), ('LOSSDEGRADE', 'LOSSDEGRADE'), ('EXPENSE', 'EXPENSE')], default='PURCHASE', max_length=11),
        ),
    ]
