# Generated by Django 4.1.1 on 2024-09-06 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuration', '0002_currency'),
        ('product', '0008_remove_product_detail_current_amount_and_more'),
        ('bill', '0006_alter_bill_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill_Receiver2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(blank=True, default=False, null=True)),
                ('approval_date', models.DateField(blank=True, default=None, null=True)),
                ('approval_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bill.bill')),
                ('bill_rcvr_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='configuration.organization')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.store')),
            ],
        ),
    ]
