# Generated by Django 4.2 on 2025-12-04 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_branch'),
        ('bill', '0007_alter_bill_bill_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch where this bill was created', null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.branch'),
        ),
    ]
