# Generated by Django 4.1.1 on 2024-09-06 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0007_bill_receiver2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bill_Receiver',
        ),
    ]
