# Generated by Django 6.0 on 2026-03-04 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0009_stripe_payment_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stripepayment',
            new_name='bill_stripe_stripe__3d71cb_idx',
            old_name='bill_models_stripe__1e2d3a_idx',
        ),
        migrations.RenameIndex(
            model_name='stripepayment',
            new_name='bill_stripe_status_a09f79_idx',
            old_name='bill_models_status_4b5c6d_idx',
        ),
        migrations.RenameIndex(
            model_name='stripepayment',
            new_name='bill_stripe_bill_id_442d39_idx',
            old_name='bill_models_bill_id_7e8f9a_idx',
        ),
        migrations.RenameIndex(
            model_name='stripewebhookevent',
            new_name='bill_stripe_event_i_22dae6_idx',
            old_name='bill_models_event_i_0a1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='stripewebhookevent',
            new_name='bill_stripe_event_t_5abea3_idx',
            old_name='bill_models_event_t_3d4e5f_idx',
        ),
        migrations.RenameIndex(
            model_name='stripewebhookevent',
            new_name='bill_stripe_created_69434c_idx',
            old_name='bill_models_created_6g7h8i_idx',
        ),
    ]
