# Generated by Django 6.0 on 2026-03-14 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0010_rename_bill_models_stripe__1e2d3a_idx_bill_stripe_stripe__3d71cb_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('stripe', 'Stripe')], help_text='Where the transaction originated', max_length=20)),
                ('event_type', models.CharField(help_text='Event name (e.g., payment_intent_created, payment_succeeded)', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', help_text='Transaction event outcome', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount related to this event', max_digits=20)),
                ('currency', models.CharField(default='USD', help_text='Currency code', max_length=3)),
                ('reference_id', models.CharField(blank=True, help_text='External reference (payment intent, charge, etc.)', max_length=255, null=True)),
                ('message', models.TextField(blank=True, help_text='Human-readable log message', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context for this log entry')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(help_text='Bill associated with this transaction event', on_delete=django.db.models.deletion.CASCADE, related_name='transaction_logs', to='bill.bill')),
                ('organization', models.ForeignKey(help_text='Organization related to this transaction', on_delete=django.db.models.deletion.PROTECT, to='configuration.organization')),
                ('user', models.ForeignKey(blank=True, help_text='User who triggered this transaction event', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction Log',
                'verbose_name_plural': 'Transaction Logs',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['bill', 'created_at'], name='bill_transac_bill_id_8f0f53_idx'),
                    models.Index(fields=['organization', 'created_at'], name='bill_trans_org_6f56f6_idx'),
                    models.Index(fields=['source', 'status'], name='bill_transac_source_bf4268_idx'),
                    models.Index(fields=['reference_id'], name='bill_trans_ref_7bce95_idx'),
                ],
            },
        ),
    ]
