# Generated by Django 6.0 on 2026-03-14 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0011_transactionlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transactionlog',
            new_name='bill_transa_bill_id_889f32_idx',
            old_name='bill_transac_bill_id_8f0f53_idx',
        ),
        migrations.RenameIndex(
            model_name='transactionlog',
            new_name='bill_transa_organiz_4ca860_idx',
            old_name='bill_trans_org_6f56f6_idx',
        ),
        migrations.RenameIndex(
            model_name='transactionlog',
            new_name='bill_transa_source_b74801_idx',
            old_name='bill_transac_source_bf4268_idx',
        ),
        migrations.RenameIndex(
            model_name='transactionlog',
            new_name='bill_transa_referen_5f823b_idx',
            old_name='bill_trans_ref_7bce95_idx',
        ),
    ]
