# Generated by Django 4.1.1 on 2024-09-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0011_alter_bill_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bill_detail',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.CharField(default='1403-06-20', max_length=10),
        ),
    ]
