# Generated by Django 6.0 on 2026-03-30 15:16

import bill.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0012_rename_bill_transac_bill_id_8f0f53_idx_bill_transa_bill_id_889f32_idx_and_more'),
        ('configuration', '0005_branch_branch_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=5, max_digits=20)),
                ('note', models.TextField(blank=True)),
                ('date', models.CharField(default=bill.models.get_date, max_length=10)),
                ('year', models.SmallIntegerField(default=bill.models.get_year)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('opposite_org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_adjustments_as_opposite', to='configuration.organization')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_adjustments_as_org', to='configuration.organization')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
    ]
