# Generated by Django 4.2 on 2025-01-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0012_alter_bill_detail_unique_together_alter_bill_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.CharField(default='1403-11-05', max_length=10),
        ),
    ]
