# Generated by Django 4.2 on 2025-05-02 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0013_bill_creator_new_bill_organization_new_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='bill_description',
            name='shipment_location',
        ),
        migrations.RemoveField(
            model_name='bill_description',
            name='store',
        ),
    ]
