# Generated by Django 4.2 on 2025-02-28 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_currency'),
        ('bill', '0013_alter_bill_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='organization_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bills_new', to='configuration.organization'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.CharField(default='1403-12-10', max_length=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='organization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bills_old', to='configuration.organization', to_field='name'),
        ),
        migrations.AlterField(
            model_name='bill_detail',
            name='item_amount',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
    ]
