# Generated by Django 4.2 on 2025-05-02 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0014_remove_bill_creator_remove_bill_organization_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='creator_new',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='organization_new',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='bill_description',
            old_name='store_new',
            new_name='store',
        ),
    ]
