# Generated by Django 4.2 on 2025-05-02 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0013_alter_product_detail_organization_and_more'),
        ('configuration', '0006_alter_organization_location_and_more'),
        ('bill', '0015_rename_creator_new_bill_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bill',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.organization'),
        ),
        migrations.AlterField(
            model_name='bill_description',
            name='shipment_location_new',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='configuration.location'),
        ),
        migrations.AlterField(
            model_name='bill_description',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.store'),
        ),
    ]
