# Generated by Django 4.2 on 2025-03-03 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0016_bill_description_store_new_alter_bill_bill_no_and_more'),
    ]

    operations = [
       
        migrations.RemoveField(
            model_name='bill_description',
            name='store',
        ),
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.CharField(default='1403-12-13', max_length=10),
        ),
    ]
