# Generated by Django 4.2 on 2025-03-08 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0022_alter_bill_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.CharField(default='1403-12-18', max_length=10),
        ),
    ]
