# Generated by Django 4.2 on 2025-10-10 11:01

import asset.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0002_alter_organization_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetBillSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_type', models.CharField(choices=[('PURCHASE', 'PURCHASE'), ('SELLING', 'SELLING'), ('PAYMENT', 'PAYMENT'), ('RECEIVEMENT', 'RECEIVEMENT'), ('LOSSDEGRADE', 'LOSSDEGRADE'), ('EXPENSE', 'EXPENSE')], default='PURCHASE', max_length=11)),
                ('total', models.DecimalField(decimal_places=5, default=0.0, max_digits=20)),
                ('payment', models.DecimalField(decimal_places=5, default=0.0, max_digits=20)),
                ('year', models.SmallIntegerField(default=asset.models.get_year)),
                ('profit', models.IntegerField(default=0)),
                ('currency', models.CharField(default='afg', max_length=7)),
                ('bill_rcvr_org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assetbillrcvrorg', to='configuration.organization')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assetbillorganization', to='configuration.organization')),
            ],
            options={
                'unique_together': {('year', 'organization', 'bill_rcvr_org', 'bill_type')},
            },
        ),
    ]
