# Generated by Django 4.2 on 2025-10-11 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_alter_organization_unique_together'),
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetWholeBillSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_type', models.CharField(choices=[('PURCHASE', 'PURCHASE'), ('SELLING', 'SELLING'), ('PAYMENT', 'PAYMENT'), ('RECEIVEMENT', 'RECEIVEMENT'), ('LOSSDEGRADE', 'LOSSDEGRADE'), ('EXPENSE', 'EXPENSE')], default='PURCHASE', max_length=11)),
                ('total', models.DecimalField(decimal_places=5, default=0.0, max_digits=20)),
                ('payment', models.DecimalField(decimal_places=5, default=0.0, max_digits=20)),
                ('profit', models.IntegerField(default=0)),
                ('currency', models.CharField(default='afg', max_length=7)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='configuration.organization')),
            ],
            options={
                'unique_together': {('organization', 'bill_type')},
            },
        ),
    ]
