# Generated by Django 4.2 on 2025-10-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_assetwholebillsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetwholebillsummary',
            name='bill_type',
            field=models.CharField(choices=[('PURCHASE', 'PURCHASE'), ('PURC_ASSET', 'PURC_ASSET'), ('SELLING', 'SELLING'), ('PAYMENT', 'PAYMENT'), ('RECEIVEMENT', 'RECEIVEMENT'), ('LOSSDEGRADE', 'LOSSDEGRADE'), ('EXPENSE', 'EXPENSE')], default='PURCHASE', max_length=25),
        ),
    ]
