# Generated by Django 4.2 on 2025-10-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_alter_assetwholebillsummary_bill_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetwholebillsummary',
            name='bill_type',
            field=models.CharField(choices=[('PURCHASE', 'PURCHASE'), ('PURCHASED_AMNT_USNG_STOCK', 'PURCHASED_AMNT_USNG_STOCK'), ('SELLING', 'SELLING'), ('PAYMENT', 'PAYMENT'), ('RECEIVEMENT', 'RECEIVEMENT'), ('LOSSDEGRADE', 'LOSSDEGRADE'), ('EXPENSE', 'EXPENSE')], default='PURCHASE', max_length=25),
        ),
    ]
