# Generated by Django 4.2 on 2025-11-06 13:45

import asset.models
import common.date
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_alter_organization_unique_together'),
        ('asset', '0005_alter_assetwholebillsummary_bill_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_value', models.DecimalField(decimal_places=5, default=0, help_text='Total value of inventory (products in stock)', max_digits=20)),
                ('cash_on_hand', models.DecimalField(decimal_places=5, default=0, help_text='Available cash (liquid asset)', max_digits=20)),
                ('accounts_receivable', models.DecimalField(decimal_places=5, default=0, help_text='Money owed by customers (SELLING - payment received)', max_digits=20)),
                ('accounts_payable', models.DecimalField(decimal_places=5, default=0, help_text='Money we owe to suppliers (PURCHASE - payment made)', max_digits=20)),
                ('loans_receivable', models.DecimalField(decimal_places=5, default=0, help_text='Money loaned out (PAYMENT - money given)', max_digits=20)),
                ('loans_payable', models.DecimalField(decimal_places=5, default=0, help_text='Money borrowed (RECEIVEMENT - money received)', max_digits=20)),
                ('total_assets', models.DecimalField(decimal_places=5, default=0, help_text='inventory + cash + receivables + loans_receivable', max_digits=20)),
                ('total_liabilities', models.DecimalField(decimal_places=5, default=0, help_text='payables + loans_payable', max_digits=20)),
                ('equity', models.DecimalField(decimal_places=5, default=0, help_text='total_assets - total_liabilities', max_digits=20)),
                ('total_revenue', models.DecimalField(decimal_places=5, default=0, help_text='Total from SELLING bills', max_digits=20)),
                ('total_cost_of_goods_sold', models.DecimalField(decimal_places=5, default=0, help_text='Total from PURCHASE bills', max_digits=20)),
                ('total_expenses', models.DecimalField(decimal_places=5, default=0, help_text='Total from EXPENSE bills', max_digits=20)),
                ('total_losses', models.DecimalField(decimal_places=5, default=0, help_text='Total from LOSSDEGRADE bills', max_digits=20)),
                ('net_profit', models.DecimalField(decimal_places=5, default=0, help_text='revenue - COGS - expenses - losses', max_digits=20)),
                ('currency', models.CharField(default='afg', max_length=7)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='asset_summary', to='configuration.organization')),
            ],
            options={
                'verbose_name': 'Organization Asset Summary',
                'verbose_name_plural': 'Organization Asset Summaries',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('PAYABLE', 'Loan Payable'), ('RECEIVABLE', 'Loan Receivable')], help_text='PAYABLE=we owe, RECEIVABLE=they owe us', max_length=15)),
                ('principal_amount', models.DecimalField(decimal_places=5, help_text='Original loan amount', max_digits=20)),
                ('amount_paid', models.DecimalField(decimal_places=5, default=0, help_text='Amount paid back so far', max_digits=20)),
                ('amount_remaining', models.DecimalField(decimal_places=5, help_text='Outstanding balance', max_digits=20)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, help_text='Annual interest rate (%)', max_digits=5)),
                ('loan_date', models.CharField(default=common.date.current_shamsi_date, max_length=10)),
                ('due_date', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAID', 'Fully Paid'), ('PARTIAL', 'Partially Paid'), ('DEFAULTED', 'Defaulted')], default='ACTIVE', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('currency', models.CharField(default='afg', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counterparty', models.ForeignKey(help_text='The organization we borrowed from or lent to', on_delete=django.db.models.deletion.PROTECT, related_name='loan_counterparties', to='configuration.organization')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='configuration.organization')),
            ],
            options={
                'ordering': ['-loan_date'],
            },
        ),
        migrations.CreateModel(
            name='ProfitLossStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(default=asset.models.get_year)),
                ('period_start', models.CharField(max_length=10)),
                ('period_end', models.CharField(max_length=10)),
                ('revenue_from_sales', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('other_revenue', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('total_revenue', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('beginning_inventory', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('purchases', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('ending_inventory', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('cogs', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('gross_profit', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('operating_expenses', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('loss_from_damage', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('net_profit', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('currency', models.CharField(default='afg', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profit_loss_statements', to='configuration.organization')),
            ],
            options={
                'ordering': ['-year', '-period_end'],
                'unique_together': {('organization', 'year', 'period_start', 'period_end')},
            },
        ),
    ]
