# Generated by Django 4.2 on 2025-12-04 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_branch'),
        ('asset', '0006_organizationasset_loan_profitlossstatement'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assetbillsummary',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='assetbillsummary',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch where these bills were processed', null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.branch'),
        ),
        migrations.AlterUniqueTogether(
            name='assetbillsummary',
            unique_together={('year', 'organization', 'bill_rcvr_org', 'bill_type', 'branch')},
        ),
    ]
