# Generated by Django 6.0 on 2026-04-13 15:15

import common.date
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_alter_assetbillsummary_unique_together_and_more'),
        ('configuration', '0005_branch_branch_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.CharField(default=common.date.current_shamsi_date, help_text='Date when the opening summary became effective', max_length=10)),
                ('cash_on_hand', models.DecimalField(decimal_places=5, default=0, help_text='Liquid cash available at the starting point', max_digits=20)),
                ('inventory_value', models.DecimalField(decimal_places=5, default=0, help_text='Value of inventory at the starting point', max_digits=20)),
                ('accounts_receivable', models.DecimalField(decimal_places=5, default=0, help_text='Money owed to the organization at the starting point', max_digits=20)),
                ('accounts_payable', models.DecimalField(decimal_places=5, default=0, help_text='Money owed by the organization at the starting point', max_digits=20)),
                ('loans_receivable', models.DecimalField(decimal_places=5, default=0, help_text='Outstanding loans receivable at the starting point', max_digits=20)),
                ('loans_payable', models.DecimalField(decimal_places=5, default=0, help_text='Outstanding loans payable at the starting point', max_digits=20)),
                ('total_revenue', models.DecimalField(decimal_places=5, default=0, help_text='Opening revenue carried into the system', max_digits=20)),
                ('total_cost_of_goods_sold', models.DecimalField(decimal_places=5, default=0, help_text='Opening cost of goods sold at the starting point', max_digits=20)),
                ('total_expenses', models.DecimalField(decimal_places=5, default=0, help_text='Opening expenses at the starting point', max_digits=20)),
                ('total_losses', models.DecimalField(decimal_places=5, default=0, help_text='Opening losses at the starting point', max_digits=20)),
                ('note', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='opening_balance', to='configuration.organization')),
            ],
            options={
                'verbose_name': 'Opening Summary',
                'verbose_name_plural': 'Opening Summaries',
            },
        ),
    ]
