# Generated by Django 4.1.1 on 2024-02-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_barcode_alter_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
