# Generated by Django 4.1.1 on 2024-03-08 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
        ('product', '0003_alter_store_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='organization',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='configuration.organization', to_field='name'),
        ),
    ]
