# Generated by Django 4.1.1 on 2024-09-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_product_detail_current_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='purchasing_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=22),
        ),
        migrations.AddField(
            model_name='stock',
            name='selling_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=22),
        ),
    ]
