# Generated by Django 4.1.1 on 2024-03-23 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_currency_alter_bill_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
