# Generated by Django 4.1.1 on 2024-09-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0008_delete_bill_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(default='PURCHASE', max_length=11),
        ),
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.CharField(default='1403-06-17', max_length=10),
        ),
    ]
