# Generated by Django 4.1.1 on 2024-09-06 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0009_alter_bill_bill_type_alter_bill_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together=set(),
        ),
    ]
