# Generated by Django 4.2 on 2025-03-01 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_currency'),
        ('bill', '0014_bill_organization_new_alter_bill_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='organization_new',
        ),
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.CharField(default='1403-12-11', max_length=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='configuration.organization'),
        ),
    ]
