# Generated by Django 4.2 on 2025-03-03 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0017_remove_bill_organization_new_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill_description',
            old_name='store_new',
            new_name='store',
        ),
    ]
