# Generated by Django 4.2 on 2025-03-04 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0020_remove_bill_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='new_creator',
            new_name='creator',
        ),
    ]
