
server {
    listen 80;
    server_name _; # accept all domain names

    root /usr/share/nginx/html; #static files live here
    index index.html;
  
    # React SPA fallback
    location / {
        try_files $uri /index.html; #default file to server
    }

    # Cache static assets aggressively
    location /static/ {
        expires 30d; # cache static js css .. for 30 days
        add_header Cache-Control "public"; 
    }

    # Don’t cache index.html (always fresh)  dont cache index.html so updates always index.html
    location = /index.html { 
        add_header Cache-Control "no-store";
    }

    # Reverse proxy API requests to backend 
    # sends /api/* to backend
    
    # --- API first ---
    location /api/ {
        proxy_pass http://tpms-backend:5000/api/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;

        proxy_buffering on;
        proxy_buffers 16 16k;
        proxy_busy_buffers_size 64k;
    }
}




