# /etc/nginx/nginx.conf  (inside the image)
user nginx;
worker_processes auto;#use all cpu automatically

events {
    worker_connections 4096; #each worker handle 4096 connections
    multi_accept on; #Accept multiple new connections at once
}

http {
    # ✅ Load standard MIME mappings (this is the missing piece)
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile on; #Faster file transfers (zero-copy).
    tcp_nopush on;#send header and  data in fewer packet
    tcp_nodelay on; # send response immediately
    keepalive_timeout 65; # keep idle connections for 65s

    # Enable gzip compression
    gzip on; 
    gzip_min_length 1024;#only comporese responses more than 1kb
    gzip_comp_level 5; #medium compression level
    gzip_types text/plain text/css application/javascript application/json application/xml application/xml+rss image/svg+xml; # comporess css plain js json xml svg
    gzip_vary on;#Send Vary: Accept-Encoding header for proxies/CDNs.
    include /etc/nginx/conf.d/*.conf;
}

