# Generated by Django 4.2 on 2025-11-15 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bill', '0007_alter_bill_bill_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.SmallIntegerField(default=1)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bill.bill')),
            ],
        ),
    ]
