# Generated by Django 4.1.1 on 2024-03-12 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bill', '0002_alter_bill_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.SmallIntegerField(choices=[(1, 'KERAYA'), (2, 'FOOD'), (3, 'BARQ'), (5, 'HOME_EXPENSE')], default=1)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bill.bill')),
            ],
        ),
    ]
