# Generated by Django 4.1.1 on 2024-03-23 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.SmallIntegerField(default=1),
        ),
    ]
