# Generated by Django 4.2 on 2025-09-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_organizationuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationuser',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('admin', 'Admin'), ('superuser', 'SuperUser'), ('owner', 'Owner')], default='member', max_length=50),
        ),
    ]
