# Generated by Django 4.2 on 2025-11-08 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_alter_organizationuser_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organizationuser',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='organizationuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
