# Generated by Django 4.2 on 2025-12-03 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_remove_organization_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0004_alter_organizationuser_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='organizationuser',
            unique_together={('user', 'organization')},
        ),
    ]
