# Generated by Django 4.2 on 2025-12-04 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_branch'),
        ('user', '0005_alter_organizationuser_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationuser',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Primary branch assignment for this user', null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.branch'),
        ),
    ]
