# Generated by Django 4.2 on 2025-03-04 11:08

import configuration.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuration', '0002_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('MANAGER', 'Manager'), ('ADMIN', 'Admin')], default='EMPLOYEE', max_length=15)),
                ('father_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=80, null=True)),
                ('address', models.CharField(blank=True, max_length=80, null=True)),
                ('jobTitle', models.CharField(blank=True, max_length=50, null=True)),
                ('id_card', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('dob', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='invalid_dob', message='Date of Birth must be in YYYY-MM-DD format', regex='^\\d{4}-\\d{2}-\\d{2}$')])),
                ('mobile', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=configuration.models.get_uuid, editable=False, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=configuration.models.upload_location)),
                ('bio', models.TextField(blank=True, null=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='configuration.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'کاربر',
            },
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.CheckConstraint(check=models.Q(('role__in', ['EMPLOYEE', 'MANAGER', 'ADMIN'])), name='valid_user_type'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(fields=('id_card',), name='unique_id_card'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(fields=('mobile',), name='unique_mobile'),
        ),
    ]
