# Generated by Django 4.2 on 2025-03-08 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('configuration', '0005_delete_languages'),
    ]
    operations = [
        migrations.AlterField(
            model_name='organization',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kdkf', to='configuration.location', to_field='city'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smt', to='configuration.organization', to_field='name'),
        ),
    ]
