# Generated by Django 4.1.1 on 2022-10-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_subservice_media_service_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_media',
            name='file',
            field=models.FileField(unique=True, upload_to='uploads/%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='subservice_media',
            name='file',
            field=models.FileField(unique=True, upload_to='uploads/%Y-%m-%d'),
        ),
    ]
