# Generated by Django 4.1.1 on 2022-10-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0009_alter_language_detail_unique_together'),
        ('products', '0013_subservice_dest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('service_name', 'dest')},
        ),
        migrations.AlterUniqueTogether(
            name='subservice',
            unique_together={('sub_service_name', 'service', 'dest')},
        ),
    ]
