# Generated by Django 4.1.1 on 2022-10-21 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0009_alter_language_detail_unique_together'),
        ('products', '0014_alter_service_service_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('service_name', 'dest', 'html_id')},
        ),
    ]
