# Generated by Django 4.1.1 on 2022-10-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0009_alter_language_detail_unique_together'),
        ('products', '0015_alter_service_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='service',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='service',
            name='html_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('dest', 'html_id')},
        ),
    ]
